### ISSUE TITLE
Backlinks not Displaying

### ISSUE THREAD

**Issue by pegasushyper** [dohliam/qownnotes-scripting#1]
First of all thank you for these awesome scripts. They're one of the reasons I even considered fully switching to QOwnNotes.
But right now I have the problem that the backlinks aren't displayed, both in QON preview window as well as in my browser. (The header renders fine)
Your cli tool retrieves the links fine. Also the preview.html is generated with the links.

```html
<h2>Backlinks</h2>

<ul>
    <li><a href="file:///home/pegasushyper/Documents/Notes/cover_pages.md"></a></li>
    <li><a href="file:///home/pegasushyper/Documents/Notes/reysuHowJournaledEvery2024.md"></a>
</li>
</ul>
```

Still the links don't render. What did I do wrong?
Also sorry to bother you.

**Comment by pegasushyper** [comment]
Looked at it again and realised it is due to line 85 in the script. It only accounts for a `#` beginning. But I use the standard without this syntax.

```markdown
This should count as title
==========================
```

I don't know if this is on purpose, but it would be nice if you could add this to the script. :smiley:

**Comment by dohliam** [comment]
Glad to hear that the scripts are useful to you!

> Looked at it again and realised it is due to line 85 in the script. It only accounts for a `#` beginning.

That makes sense -- as you discovered, the script just uses a simple pattern to match ATX-style headings (i.e., `#` at the beginning of a line). At first glance, accommodating Setext headings would require either a much more complicated regex (which might be slower as a result), or perhaps properly serializing the whole markdown document first. (Actually this is one of the reasons I prefer ATX-style headings...)

I'm surprised this works with Setext headings at all in the CLI version as I seem to recall it making similar assumptions.

However, looking back at the QML code now, I think it might be possible to do this a different way, assuming that there is a method of getting the title of a note from the Note object through the QOwnNotes API instead. So instead of what is on line 85 now, it would have something like `var text = pageObj.title;`. However, I can't seem to find a way to get the note title from the note object in the documentation.

For now I would suggest opening an issue at [qownnotes/scripts](https://github.com/qownnotes/scripts) as the maintainers may know if there is a better way to implement this.

**Comment by pegasushyper** [comment]
I just rolled with the QON standard of setext headers. As you suggested I opened a new [issue at the QON script repo](https://github.com/qownnotes/scripts/issues/227) Thank you for your reply. I will close this one in turn because I guess it has no purpose anymore then.
